### ISSUE TITLE
add mouse4 and mouse5 as a bindable option

### ISSUE THREAD

**Issue by Beethoven-n** [dreamcat4/skippy-xd#133]
i want to scroll up and down to do the same thing as keysNext and keysPrev, but mouse4 and mouse5 are not recognized either as a miwMouse4/5 option, nor as keysyms to register.
pls add thank u

**Comment by dreamcat4** [comment]
can you launch the program `xev` and then press mouse buttons? does it print anything registered in the terminal output?

do you have a software for support of your mouse like piper for logitech? can that help to assign custom actions to buttons 4,5 ?

**Comment by felixfung** [comment]
The caveat is eliminated
