### ISSUE TITLE
[request] show hidden/minimized/iconified windows

### ISSUE THREAD

**Issue by biopsin** [dreamcat4/skippy-xd#15]
Hi,
first thank you for maintaining skippy-xd.
I'm wondering if someone have being pondering on it :)
The work around : https://github.com/hotice/webupd8/blob/master/skippy-xd-fix

**Comment by ginhiki** [comment]
yes this would be a great improvement

**Comment by vredesbyyrd** [comment]
@biopsin  

Hi, thanks for the workaround. Does step 7 (minimize hidden windows unless selected) laid out in the script work for you? I have hacked on it a bit without success. On `2bwm` btw.

**Comment by biopsin** [comment]
@vredesbyyrd probably why 2bwm TODO: Extended Window Manager Hints (EWMH)

**Comment by vredesbyyrd** [comment]
@biopsin 

thanks, dont know how I missed that. I got around the issue by changing step 7 in the script to: 

```
#7.
hidden=${hidden/$SkippySelected}
for item in $hidden; do
  xdotool windowactivate $item
  xdotool windowminimize $item
done
```

First focusing/activating the window seemed to "fix" it.
