### ISSUE TITLE
AwesomeWM only shows windows from current tag

### ISSUE THREAD

**Issue by kaykay38** [dreamcat4/skippy-xd#17]
I am on Awesome WM and skippy-xd only shows the windows from the current tag. I am running `skippy-xd` mapped to hotkeys not as a daemon. I don't know if it's Awesome WM or if it's skippy-xd that's preventing me from seeing the other windows.

**Comment by vredesbyyrd** [comment]
Hi. 

Im experiencing the same on `2bwm`. My uneducated guess is its because both awesome & 2bwm use `xcb` as opposed to `xlib`. 

I know basically nothing about `Xorg` but it would be real nice if we could get skippy to work with both `xlib` and `xcb`, assuming that is the issue.
