### ISSUE TITLE
Some issues or suggestions for improving this tool:

### ISSUE THREAD

**Issue by 1Renus** [dreamcat4/skippy-xd#19]
Some issues or suggestions for improving this tool:
1) Set the default desktop wallpaper to skippy-xd background.
2) When showing the desktop, all thumbnails disappear in skippy-xd it only shows icons.
3) It would be better if it had a border around selected windows instead of highlighting it.
4) I don't want to disable panel after activating or launching skippy-xd.
5) Workaround for minimized windows.

**Comment by felixfung** [comment]
1. The default background in skippy should be the your existing wallpaper, is that what you mean?
2. Sorry I don't understand?
3. Nice idea. May be implemented in the future.
4. Also nice idea. May be implemented in the future.
5. Done!
