### ISSUE TITLE
Showing minimized windows

### ISSUE THREAD

**Issue by felixfung** [dreamcat4/skippy-xd#36]
Showing thumbnail of minimized windows seem to be a very popular request/feature.

From code inspection, looks like in the main loop, the polling of the UnmapNotify XEvent is responsible for current minimized window behaviour...

It is handled similarly, but not identically, to that of closing a window. Most importantly, the pixmap and picture of the window are freed.

This feature is probably quite achievable by changing the code here, as well as handling wattr.map_state == IsViewable.

I suspect windows in other virtual desktops might be similarly or identically managed, based on IsViewable and unmapping... this would be dependent on the particular WM.

In addition, visual cues (e.g. some sort of icon and/or tinting configuration etc) needs to be implemented for minimized windows, to distinguish minimized windows from other ones.

By the way, for the window closing event, the "Last client window destroyed/unmapped, exiting." thing, wouldn't that mess up daemon mode? Daemon mode should persist regardless of whether there are active windows at all?

**Comment by dreamcat4** [comment]
> By the way, for the window closing event, the "Last client window destroyed/unmapped, exiting." thing, wouldn't that mess up daemon mode?

that's a great question! i never actually considered what happens with 0 windows open. It would be an interesting thing to try / find out

> Daemon mode should persist regardless of whether there are active windows at all?

yes, absolutely correct

**Comment by felixfung** [comment]
> > By the way, for the window closing event, the "Last client window destroyed/unmapped, exiting." thing, wouldn't that mess up daemon mode?
> 
> that's a great question! i never actually considered what happens with 0 windows open. It would be an interesting thing to try / find out
> 
> > Daemon mode should persist regardless of whether there are active windows at all?
> 
> yes, absolutely correct

It terminates the expose activity, without killing the daemon, which persists.
