### ISSUE TITLE
Keep going!

### ISSUE THREAD

**Issue by Iiari** [dreamcat4/skippy-xd#4]
Just wanted to give you support and encouragement in your work.  I think Skippy is a pretty critical piece of software, and using it is the only thing that makes the Budgie DE work for me.  Keep it up!

**Comment by ftoledo** [comment]
We thinking on re-add it to Huayra GNU/Linux. I hope that continue supporting too!

**Comment by ftoledo** [comment]
I will build and test this fork instead of richardgv. Thanks!

**Comment by ftoledo** [comment]
good news!. I will check it! thanks!
