### ISSUE TITLE
Daemon crashes(Segmentation fault)

### ISSUE THREAD

**Issue by cezaris13** [dreamcat4/skippy-xd#43]
System Info:
```
Kernel: 6.1.12-arch1-1 
WM: dwm
```
I recently updated skippy-xd package (great work!), animation feature looks really nice, but I found out that running the command: ```skippy-xd --start-daemon``` returns:
![image](https://user-images.githubusercontent.com/32205463/221657089-bbdfde03-d94b-43c6-a2eb-d062ae0800e3.png)

By checking the commits, found that after https://github.com/dreamcat4/skippy-xd/commit/90509426c78b636f28fe40585077bc79b935635c commit the segmentation fault problem occurs.  

I'll try to look into this problem, if I have some time.

**Comment by felixfung** [comment]
Thanks for the bug report.

Commit https://github.com/dreamcat4/skippy-xd/pull/41/commits/aac46173e657d3d831e8a8957bc990436642e9d6 from should fix it.

Please feel free to create new PR and merge this commit.

**Comment by dreamcat4** [comment]
closed by commit 61f979b
