### ISSUE TITLE
Reload config file for daemon

### ISSUE THREAD

**Issue by felixfung** [dreamcat4/skippy-xd#48]
Right now, the config file is read in the start of the app. This applies to both daemon and non-daemon mode, with the latter simply passing command to the former. Hence, for daemon mode, the only way to load different config options is to kill the current daemon, and restart.

However, persistent daemon is needed for storing and showing minimized windows thumbnails #36. Hence, with the current code, to reload config file means to lose some existing thumbnails.

It looks to me (not 100% certain) config file reading and loading can be refactored into one function, and then objects (e.g. MainWin and ClientWin) appropriately updated. Then, a daemon command with argument can be passed to reload config file.

**Comment by felixfung** [comment]
@dreamcat4 you have worked on the pipe area previously right? It looks to me it has always been designed to take in only one character command, never designed to take argument: in this case we would want to pass the config file path as argument. I don't know if passing a C-style string in the config would be straightforward or complicated, perhaps it's as simple as passing the string length and then the string, but then more fundamentally we are extending the protocol?

What exactly is the issue with named pipe? Is it within the context of alt-tab usage, it is sometimes dropping keyboard events and sometimes duplicating keyboard events? So far in my limited usage I have never experienced any issues with named pipes.

**Comment by felixfung** [comment]
By the way this is a good idea: https://github.com/richardgv/skippy-xd/pull/62/files. Using UID limits usage to skippy to one use per user, which is not the most general? Maybe a simple random postfix is the best?

**Comment by dreamcat4** [comment]
ok so... my initial knee jerk instinct here is to not implement passing of config file path through named pipe in the first attempt. And instead just reload the same config file that skippy daemon was originally launched with.

The simpler version can then more easily be implemented, deferring anything more complex for a 2nd seperate changeset.
