### ISSUE TITLE
Why are there so so so many debug prints?

### ISSUE THREAD

**Issue by felixfung** [dreamcat4/skippy-xd#49]
I mean I put in lots of printfs myself, but I try to remove/comment out before merging. Should existing printfs be commented out?

Or we could put in a command line option to switch on/off prints?

**Comment by dreamcat4** [comment]
> Or we could put in a command line option to switch on/off prints?

yeah the 2nd option, i would prefer

**Comment by dreamcat4** [comment]
But to be a bit clear(er) - there are the sort of temporary debug lines that are for bug hunting, which are not as useful

then there are more generally informative statements which can be regarded as a sort-of-alternative to inline code comments (or inline documentation). That then is actually worth keeping in there. And holds a better justification / higher value
