### ISSUE TITLE
Can't cycle windows in fluxbox

### ISSUE THREAD

**Issue by slackhead** [dreamcat4/skippy-xd#5]
I can't seem to get this to work at all.  My setup:

Mod1 Tab :Exec skippy-xd --activate-window-picker

I'm using the default config, but I changed the 3 lines that move the mouse to false as I don't use the mouse. I also tried the -runner alternative.  I have a couple of terminal windows open to test with.

When I press alt-tab I see a preview of the terminals, but holding alt and pressing tab again doesn't focus the next window. If I press right arrow then the terminal windows go white and I have to keep pressing alt-tab-left until a release will exit back to the desktop.  Otherwise I have to ctrl-alt-backspace to kill X.

The original version did at least cycle using arrows, but I couldn't work out how to bind keys.  I would very much like to get this working.  I've attached the output when I press tab.
[skippy.txt](https://github.com/dreamcat4/skippy-xd/files/3060795/skippy.txt)

**Comment by lafleurdeboum** [comment]
Have you tried to bind to `skippy-xd-runner --next` ? In ~/.fluxbox/keys, you could use
`Mod1 Tab :Exec skippy-xd-runner --next`
This should bring the Exposé up with the focus on next window. This _should_ work when you type Tab twice. I must confess it fails on my fluxbox. I use 
`Super_L :Exec skippy-xd-runner --toggle-window-picker`
Which treats the Windows key as a normal input (`Mod4` is a modified modifier input, with no keyRelease event). Then you press the windows key once, it brings the chooser up, and tab does circle between windows.
