### ISSUE TITLE
What do includeAllScreens and avoidThumbnailsFromOtherScreens do?

### ISSUE THREAD

**Issue by felixfung** [dreamcat4/skippy-xd#50]
They are not in the sample config file.

From code inspection, it looks like includeAllScreens and avoidThumbnailsFromOtherScreens are only used in 

https://github.com/dreamcat4/skippy-xd/blob/61f979b16ec6b67d94f7956670c3c35c36e7bdc4/src/clientwin.c#L168

which evaluates so that the if() clause becomes true anyway.

includeAllScreens is also used in

https://github.com/dreamcat4/skippy-xd/blob/61f979b16ec6b67d94f7956670c3c35c36e7bdc4/src/wm.c#L395

which can be substituted with showAllDesktops.

I am inclined to remove these two configs?

**Comment by dreamcat4** [comment]
yeah i agree with your assessment and support the removal of that option
