### ISSUE TITLE
Evangelize

### ISSUE THREAD

**Issue by felixfung** [dreamcat4/skippy-xd#82]
Help wanted for evangelization! To let X users know that we have/soon will have a good, lightweight, customizable, window-manager-agnostic composite window selector! Feast the eyes with the eye-candies of beautiful screenshots and videos!

... While I work on the code.

Some obvious target audience include various Linux distro forums. I also found https://www.reddit.com/r/unixporn/, don't know if that's something that will be well received there. Beyond that, I don't know too much about the ecosystems and communities.

Thanks!

**Comment by revast** [comment]
That would definitely help, 
- Plus proper packaging (via [OBS](https://openbuildservice.org/help/manuals/obs-user-guide/art.obs.bg.html), one would catch a lot, rpm, deb, arch, flatpak, appimage....),
- track Package Status for various distributions... and hopefully getting into repositories again.
- reddit/r/linux is also well-visited. 
- What's more, this application was used and recomended before (-> argument against a new name), so one can definitely post on these places about it, update Arch, Ubuntu, Debian Wiki etc.... 
- Well, there even is a [wikipedia entry for it](https://en.wikipedia.org/wiki/Skippy_(X)) (!)

**Comment by felixfung** [comment]
Thanks @revast 

@dreamcat4 can we open a wiki on this repo, so we can put in various topics, including usage, setup (migrate much of the current readme.md there, it's very long and detailed), config, distro adoptions, history, screenshots, etc?

**Comment by vredesbyyrd** [comment]
Agreed, getting more eyeballs on this project could be very helpful. I had not seen this issue yet, but I made a [post](https://www.reddit.com/r/unixporn/comments/12dwrul/2bwm_skippyxd_animations/) about skippy on r/unixporn last weeek with that in mind.

The post insights shows 12,6000 views and it seemed well received generally - this was my first post in that community.

**Comment by felixfung** [comment]
Hi guys, please keep evangelism. I am still working on the code. Somehow doing a translucent (but not transparent) window to mark highlighted desktop for paging mode is *$&#^.... that got me stuck all this time, but I am working on it.

Meanwhile, please spread the word to different communities. I guess there are plenty of X users who would like to at least try skippy, right?

@dreamcat4 can you please create wiki? I cannot do it as collaborator. I think something like https://github.com/felixfung/skippy-xd/wiki would be good organization for different info?

**Comment by dreamcat4** [comment]
@felixfung Yes sorry for not seeing your request earlier. I have been too busy with other work to keep up / give a good participation. My apologies. Yes - wiki and discussions enabled.

If you ever want to change this repo to an actual Organization (if you change mind of feel becomes justified, for better project management and visibility)... then please let me know when it becomes worthwhile. And just suggest to create a github org as "skippy-xd/skippy-xd". Many thanks for your continued participation and efforts here in my absence.

**Comment by felixfung** [comment]
I'm wondering if it would be a good idea to make the wiki editable for everyone?

**Comment by dreamcat4** [comment]
> I'm wondering if it would be a good idea to make the wiki editable for everyone?

ok its a good question, was not so sure myself the implications here. setting is changed now. if anybody else ever wants access to improve those documentation then it can always be considered later...

in fact i also opened discussions tab section. so that is an alternative place where people can make posts on besides the wiki

**Comment by felixfung** [comment]
I just posted on https://bbs.archlinux.org/viewtopic.php?pid=2100278#p2100278. The forum seems to have vibrant following. Ubuntu forum seems not to have as much traffic as I thought? Debian forum has some weird issue and I can't activate my account...

What are some communities we should target?

@vredesbyyrd can you please post on reddit/r/linux?

**Comment by vredesbyyrd** [comment]
Good call on r/linux, I'm out of town right now, but will post as soon as I'm able to.

**Comment by felixfung** [comment]
Notifying past contributors and all those who love skippy: skippy-xd has new features including animation, new layout, live preview of unmapped windows, new mode, and more. Please feel free to check out the app and wiki :)

@richardgv @antonio-malcolm @maclomhair @MichaelStraube @penguinpowernz @landroni @stuffo @honsiorovskyi @honsiorovskyi @nick87720z @dobkeratops @PaulJ505 @raman08 @1Renus @justpeanuts @imthenachoman @chamabreu @robcsi @qifeikji @elamperti @Qu4tro @num3throd @callmetango @gokhanckgz @aki-s @lujanfernaud @heshdotcc @LC43 @vviikk @IvanMalison @rdrms @ brunofunnie @sagittarius-ae @leonardssh @guwnghoa @devxpy @locness3 @aster94 @pszi1ard @chopfitzroy @fpytloun @chopfitzroy @fulgorit @docnoe @gazeto @FHFS @daljeet-hcl @Gjum @danrobi11 @LordReg @pfr-dev @LindyBalboa @crowell @4iar @brunofunnie @keevitaja @ghost @grimnak @avernan @javl @mustafaozhan @dicktyr @lotabout @Gjum @4drift @acrisci @ftoledo @alejandro-perez @Ianrat @ochosi @acidtonic @cefn @ViktorNova @spymastermatt @alejandro-perez @stome @jchtt @actionless @tblancher @z @bitthegeek @antis81 @atsepkov  @gavsiu @arkq @obadz @lujanfernaud @gianlucapettinello @elerocks @alonswartz @icarito @ikem-krueger @lafleurdeboum @uvisgrinfelds @ikem-krueger @salcin @foltiz @tillmann @morgan-greywolf @atenrok @sagotsky @dooblem @nkkollaw @iicybeii @ dobkeratops @penguinpowernz @tdy @tcyrus @mouarfff @devsnd @fazjaxton @honsiorovskyi @gi1242 @imthenachoman @ozls @RaafatTurki @jzbor @kaykay38 @GreenLunar @biopsin @g--o @wokawoka @lafleurdeboum @rik-shaw @danrobi11 @slackhead @Iiari @curusarn @sgon00 @v4dkou @dustincys

**Comment by IvanMalison** [comment]
woah. Live preview of unmapped windows? thats awesome!

**Comment by locness3** [comment]
Thanks, I'll check it out!
