### ISSUE TITLE
multi-monitor support

### ISSUE THREAD

**Issue by g--o** [dreamcat4/skippy-xd#9]
About dual monitor support:
* is there a way to make both monitors in expose at the same time?
* is there a way to make the background parameter in the config an array (one per screen)?

I think I might be able to come up with workarounds but I think it's better to have it builtin. If it's not too complex I might be able to help develop it as well given some pointers

**Comment by dreamcat4** [comment]
Yes the thing you will need to do here is dig deeper into the code and see. Then come back if you have anything more specific that you would like to propose. At that point we can have a further discussion about it.

Broadly speaking I'm not opposed to such changes as long as they are not going to be too risky for everybody else who isn't using those feature(s).

**Comment by g--o** [comment]
Alright, I'll have a look once I find the time. Are features being actively developed at the moment or do you only maintain / support?

**Comment by dreamcat4** [comment]
Maintenance mode at the moment. Until I can ever free up my schedule again.

**Comment by felixfung** [comment]
xinerama is supported, but I have no idea how
